language: node_js
before_install:
  - npm install -g grunt-cli
  - npm uninstall grunt # https://github.com/npm/npm/issues/3958
  - npm install -g bower
node_js:
  - "0.10"
after_script:
  - npm install -g istanbul
  - npm run coveralls